//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESExpressApp.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESExpressApp.Resources.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ls_Add {
            get {
                return ResourceManager.GetString("ls_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air transportation.
        /// </summary>
        internal static string ls_Airtransportation {
            get {
                return ResourceManager.GetString("ls_Airtransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ls_Areyousure {
            get {
                return ResourceManager.GetString("ls_Areyousure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived at warehouse.
        /// </summary>
        internal static string ls_Arrivedatwarehouse {
            get {
                return ResourceManager.GetString("ls_Arrivedatwarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string ls_Calculate {
            get {
                return ResourceManager.GetString("ls_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        internal static string ls_Calculator {
            get {
                return ResourceManager.GetString("ls_Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ls_Changepassword {
            get {
                return ResourceManager.GetString("ls_Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change phone number.
        /// </summary>
        internal static string ls_Changephonenumber {
            get {
                return ResourceManager.GetString("ls_Changephonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ls_Close {
            get {
                return ResourceManager.GetString("ls_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ls_ConfirmPassword {
            get {
                return ResourceManager.GetString("ls_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        internal static string ls_Connectionerror {
            get {
                return ResourceManager.GetString("ls_Connectionerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ls_Continue {
            get {
                return ResourceManager.GetString("ls_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ls_Delete {
            get {
                return ResourceManager.GetString("ls_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District (city).
        /// </summary>
        internal static string ls_District {
            get {
                return ResourceManager.GetString("ls_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ls_Edit {
            get {
                return ResourceManager.GetString("ls_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string ls_Editprofile {
            get {
                return ResourceManager.GetString("ls_Editprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ls_Error {
            get {
                return ResourceManager.GetString("ls_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code from SMS sent to {phone}.
        /// </summary>
        internal static string ls_Etcfsstphone {
            get {
                return ResourceManager.GetString("ls_Etcfsstphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently askedquestions.
        /// </summary>
        internal static string ls_Faq {
            get {
                return ResourceManager.GetString("ls_Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ls_Forgotyourpassword {
            get {
                return ResourceManager.GetString("ls_Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get verification code.
        /// </summary>
        internal static string ls_Getverificationcode {
            get {
                return ResourceManager.GetString("ls_Getverificationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ls_Height {
            get {
                return ResourceManager.GetString("ls_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ls_Help {
            get {
                return ResourceManager.GetString("ls_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string ls_Home {
            get {
                return ResourceManager.GetString("ls_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How we  work.
        /// </summary>
        internal static string ls_Howwework {
            get {
                return ResourceManager.GetString("ls_Howwework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In transit.
        /// </summary>
        internal static string ls_Intransit {
            get {
                return ResourceManager.GetString("ls_Intransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is deleted or id is wrong.
        /// </summary>
        internal static string ls_Isdeletedoridiswrong {
            get {
                return ResourceManager.GetString("ls_Isdeletedoridiswrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string ls_Length {
            get {
                return ResourceManager.GetString("ls_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string ls_Loading {
            get {
                return ResourceManager.GetString("ls_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Order.
        /// </summary>
        internal static string ls_Myorder {
            get {
                return ResourceManager.GetString("ls_Myorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New phone number.
        /// </summary>
        internal static string ls_Newphonenumber {
            get {
                return ResourceManager.GetString("ls_Newphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        internal static string ls_Nodataavailable {
            get {
                return ResourceManager.GetString("ls_Nodataavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not shipped.
        /// </summary>
        internal static string ls_Notshipped {
            get {
                return ResourceManager.GetString("ls_Notshipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong. please try again later..
        /// </summary>
        internal static string ls_Oopserror {
            get {
                return ResourceManager.GetString("ls_Oopserror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ls_Password {
            get {
                return ResourceManager.GetString("ls_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        internal static string ls_Passwordrecovery {
            get {
                return ResourceManager.GetString("ls_Passwordrecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset complete.
        /// </summary>
        internal static string ls_Passwordresetcomplete {
            get {
                return ResourceManager.GetString("ls_Passwordresetcomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection or try again.
        /// </summary>
        internal static string ls_Pcyicta {
            get {
                return ResourceManager.GetString("ls_Pcyicta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        internal static string ls_Personalinfo {
            get {
                return ResourceManager.GetString("ls_Personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string ls_Phone {
            get {
                return ResourceManager.GetString("ls_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ls_ProductName {
            get {
                return ResourceManager.GetString("ls_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ls_Profile {
            get {
                return ResourceManager.GetString("ls_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string ls_Register {
            get {
                return ResourceManager.GetString("ls_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful.
        /// </summary>
        internal static string ls_Registrationsuccessful {
            get {
                return ResourceManager.GetString("ls_Registrationsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string ls_Remark {
            get {
                return ResourceManager.GetString("ls_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        internal static string ls_Resendcode {
            get {
                return ResourceManager.GetString("ls_Resendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string ls_Retry {
            get {
                return ResourceManager.GetString("ls_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ls_Save {
            get {
                return ResourceManager.GetString("ls_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ls_Search {
            get {
                return ResourceManager.GetString("ls_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary phone number.
        /// </summary>
        internal static string ls_Secondaryphone {
            get {
                return ResourceManager.GetString("ls_Secondaryphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string ls_Selectlanguage {
            get {
                return ResourceManager.GetString("ls_Selectlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ls_Services {
            get {
                return ResourceManager.GetString("ls_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ls_Settings {
            get {
                return ResourceManager.GetString("ls_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping address.
        /// </summary>
        internal static string ls_Shippingaddress {
            get {
                return ResourceManager.GetString("ls_Shippingaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping costs.
        /// </summary>
        internal static string ls_Shippingcosts {
            get {
                return ResourceManager.GetString("ls_Shippingcosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping methods.
        /// </summary>
        internal static string ls_Shippingmethods {
            get {
                return ResourceManager.GetString("ls_Shippingmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string ls_Signin {
            get {
                return ResourceManager.GetString("ls_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string ls_Submit {
            get {
                return ResourceManager.GetString("ls_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train transportation.
        /// </summary>
        internal static string ls_Traintransportation {
            get {
                return ResourceManager.GetString("ls_Traintransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string ls_Transactioncompleted {
            get {
                return ResourceManager.GetString("ls_Transactioncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck transportation.
        /// </summary>
        internal static string ls_Trucktransportation {
            get {
                return ResourceManager.GetString("ls_Trucktransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ls_Warning {
            get {
                return ResourceManager.GetString("ls_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill  number.
        /// </summary>
        internal static string ls_Waybillnumber {
            get {
                return ResourceManager.GetString("ls_Waybillnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string ls_Weight {
            get {
                return ResourceManager.GetString("ls_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What clients say.
        /// </summary>
        internal static string ls_Whatclientssay {
            get {
                return ResourceManager.GetString("ls_Whatclientssay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ls_Width {
            get {
                return ResourceManager.GetString("ls_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can get a new code in {time} seconds.
        /// </summary>
        internal static string ls_Ycgancits {
            get {
                return ResourceManager.GetString("ls_Ycgancits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string ls_Yourname {
            get {
                return ResourceManager.GetString("ls_Yourname", resourceCulture);
            }
        }
    }
}
